name: workflows
on:
  push:
    branches:
      - master

jobs:
  build_docker_image:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          echo "Generated image tag is ${{ github.sha }}"
          docker build -t kunlekush/springboot:app-${{ github.sha }} .
          echo "Docker Build Completed

  push_image_to_registry:
    runs-on: self-hosted
    needs: build_docker_image
    steps:
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker Image to Registry
        run: docker push kunlekush/springboot:app-${{ github.sha }}
